apiVersion: batch/v1
kind: Job
metadata:
  name: {{ .Release.Name }}-migrations-{{ .Release.Revision }}
spec:
  template:
    metadata:
      name: migrations
    spec:
      containers:
        - name: main
          image: debian:10-slim
          command: ["/bin/sh", "-c"]
          args: ["sleep 10"]
      restartPolicy: Never
