apiVersion: v1
kind: Service
metadata:
  name: {{.Release.Name}}-redis
  labels:
    project: counter
spec:
  selector:
    release: {{ .Release.Name }}
    project: counter
    app: redis
  ports:
    - port: 6379
